"use client";
import { useEffect, useRef } from "react";
import Link from "next/link";
import { AssetIcon, eventAsset, Pio } from "@/components/Brand";
import { useTimeline } from "@/components/timeline/TimelineStore";
import { setFinEventStatus } from "@/lib/domain/state";
import { computeReadiness } from "@/lib/domain/readiness";
import { daysUntil, formatEventDate, type LifeEvent } from "@/lib/domain/timeline";
const LABEL = { confirmed: "✓ 확정", expected: "◇ 예상", goal: "☆ 목표" };
export function EventDrawer({ event, onClose }: { event: LifeEvent; onClose: () => void ;}) {
  const { state, update } = useTimeline(); const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { const el = dialog.current; const prior = document.activeElement as HTMLElement | null; const overflow = document.body.style.overflow; el?.showModal(); document.body.style.overflow = "hidden"; return () => { el?.close(); document.body.style.overflow = overflow; prior?.focus() ;} ;}, []);
  const checks = state.finEvents.filter(f => f.lifeEventId === event.id).sort((a, b) => (a.dueDate ?? "").localeCompare(b.dueDate ?? "")); const completed = checks.filter(f => f.status === "completed").length; const ratio = checks.length ? Math.round(completed / checks.length * 100) : 0; const d = daysUntil(event.date);
  const financial = state.financialContext; const hasFinancial = financial?.savings !== undefined && financial?.emergencyFund !== undefined && financial?.monthlyIncome !== undefined && financial?.monthlyExpense !== undefined; const readiness = hasFinancial ? computeReadiness(event, checks, financial) : null;
  return <dialog ref={dialog} className="fin-dialog" aria-labelledby="event-title" onCancel={e => { e.preventDefault(); onClose() ;}} onClick={e => { if (e.target === e.currentTarget) onClose() ;}}><div className="drawer-layout"><header className="drawer-header"><AssetIcon name={eventAsset(event)} size={64} /><div><span className={`status-badge ${event.certainty}`}>{LABEL[event.certainty]}</span><h2 id="event-title">{event.title}</h2><p>{formatEventDate(event.date)}{d !== null && d > 0 ? ` · D-${d}` : ""}</p></div><button onClick={onClose} className="icon-button" aria-label="이벤트 상세 닫기" autoFocus>×</button></header>
    <div className="drawer-content"><section><div className="readiness-header"><h3>준비 체크포인트</h3><strong>{completed}<small style={{ fontSize: 14, color: "#637580" }}> / {checks.length}</small></strong></div><div className="progress-track" role="progressbar" aria-label="체크포인트 완료율" aria-valuenow={ratio} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${ratio}%` }} /></div><p style={{ marginTop: 10 }}>완료한 준비를 표시하면 다음 할 일을 살펴보기 쉬워요.</p></section>
      <section>{checks.length > 0 ? <><h3>하나씩 준비해요</h3>{checks.map(f => <label key={f.id} className={`checklist-row ${f.status === "completed" ? "done" : ""}`}><input type="checkbox" checked={f.status === "completed"} onChange={e => update(s => setFinEventStatus(s, f.id, e.target.checked ? "completed" : "pending"))} /><span><strong>{f.title}</strong>{f.note && <small>{f.note}</small>}<small>{formatEventDate(f.dueDate)} 예정</small></span></label>)}</> : <div className="unknown-readiness"><h3>아직 체크포인트가 없어요.</h3><p>피오에게 이 계획을 위해 무엇을 준비하면 좋을지 물어보세요.</p></div>}</section>
      {readiness ? <section><div className="readiness-header"><h3>금융 준비도</h3><strong>{readiness.overallScore}%</strong></div><p>입력한 금융정보와 체크포인트에 따른 참고 지표예요.</p><div className="readiness-dims">{readiness.dimensions.map(dim => <div key={dim.key}><label>{dim.label}</label><div className="progress-track"><span style={{ width: `${dim.score}%` }} /></div><span>{dim.score}%</span></div>)}</div></section> : <section className="unknown-readiness"><h3>금융 준비도 · 확인 필요</h3><p>소득·지출·저축·비상금 정보가 충분하지 않아 점수를 표시하지 않았어요.</p></section>}
      <section className="drawer-insight"><Pio mood={completed === checks.length && checks.length > 0 ? "celebrate" : "guide"} size={48} /><div><strong>피오의 한마디</strong><p>{event.status === "past" ? "지나온 경험도 다음 계획의 소중한 출발점이에요." : d !== null && d > 0 ? `${event.title}까지 약 ${Math.max(1, Math.round(d / 30))}개월 남았어요. 예정된 체크포인트부터 차근차근 확인해보세요.` : "정확한 시점을 알게 되면 준비 계획을 더 구체적으로 세울 수 있어요."}</p></div></section>
      <Link href="/opportunities" className="aside-item"><AssetIcon name="utility-opportunity" size={44} /><span><strong>함께 확인할 기회</strong><small>내 계획과 관련된 청년지원 살펴보기</small></span><span className="chevron">›</span></Link></div>
    <footer className="drawer-footer"><Link href={`/ask?event=${encodeURIComponent(event.id)}`} className="button button-primary">피오에게 {event.title} 계획 물어보기 ↗</Link></footer></div></dialog>;
}
